### PR TITLE
[ADD TOKEN]Pepe

### PR DESCRIPTION
**Pull request by xhy0001**
https://discord.gg/YtN5SXCh

### CODE REVIEW

**Comment by Antares-RXD** [comment]
Please, add [ADD TOKEN] in the title of PR

**Comment by xhy0001** [comment]
> Please, add [ADD TOKEN] in the title of PR
Is that okay?

**Comment by Antares-RXD** [comment]
you've got some things wrong-


- It's a PR and you want to put in two tokens. You should go 1 to 1.
- In website and twitter you should put the official one of your token, if it doesn't have, leave it empty and in the future you can ask to fill it.

**Comment by xhy0001** [comment]
Thank you. Deleted and changed.

**Comment by Antares-RXD** [comment]
Thanks!

**Pull request merged**
